apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: wordpress-sophie
bases:
  - ../base

commonAnnotations:
  domain: sophie.raynix.info
  cert: wordpress-sophie-cert

patchesStrategicMerge:
  - patch.yaml

images:
  - name: ghcr.io/raynix/backup
    newTag: v0.28

resources:
  - ns.yaml
  - ss.yaml
  - pv.yaml
