apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: wordpress-raynix
bases:
  - ../base

commonAnnotations:
  domain: raynix.info
  cert: wordpress-raynix-cert

patchesStrategicMerge:
  - patch.yaml

images:
  - name: ghcr.io/raynix/backup
    newTag: v0.28

resources:
  - ns.yaml
  - ss.yaml
  - pv.yaml
