---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: wordpress
spec:
  resources:
    requests:
      storage: 10Gi
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: wordpress
spec:
  replicas: 3