apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: wordpress-ronia
bases:
  - ../base

commonAnnotations:
  domain: ronia.raynix.info
  cert: wordpress-ronia-cert

patchesStrategicMerge:
  - patch.yaml

images:
  - name: ghcr.io/raynix/backup
    newTag: v0.28

resources:
  - ns.yaml
  - ss.yaml
  - pv.yaml
