apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
configurations:
  - conf.yaml

resources:
  - deploy.yaml
  - pvc.yaml
  - service.yaml
  - redis.yaml
  - cronjob-backup.yaml
  # with istio
  - virtual-service.yaml
  - gateway.yaml
  # with ingress-nginx
  #- ingress.yaml

configMapGenerator:
  - name: nginx-config
    files:
      - nginx.conf
  - name: php-config
    files:
      - php.ini
  - name: wordpress-nginx-config
    files:
      - wordpress-nginx.conf

vars:
  - name: DOMAIN
    objref:
      apiVersion: apps/v1
      kind: Deployment
      name: wordpress
    fieldref:
      fieldpath: metadata.annotations.domain
  - name: CERT
    objref:
      apiVersion: apps/v1
      kind: Deployment
      name: wordpress
    fieldref:
      fieldpath: metadata.annotations.cert
